{{- if not .Values.apiKeys.existingSecret }}
{{- if or .Values.apiKeys.anthropic .Values.apiKeys.openai .Values.apiKeys.gemini .Values.apiKeys.openrouter }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "thclaws.fullname" . }}-api-keys
  labels:
    {{- include "thclaws.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.apiKeys.anthropic }}
  anthropic-api-key: {{ .Values.apiKeys.anthropic | quote }}
  {{- end }}
  {{- if .Values.apiKeys.openai }}
  openai-api-key: {{ .Values.apiKeys.openai | quote }}
  {{- end }}
  {{- if .Values.apiKeys.gemini }}
  gemini-api-key: {{ .Values.apiKeys.gemini | quote }}
  {{- end }}
  {{- if .Values.apiKeys.openrouter }}
  openrouter-api-key: {{ .Values.apiKeys.openrouter | quote }}
  {{- end }}
{{- end }}
{{- end }}
---
{{- if and .Values.multiTenant.enabled (not .Values.multiTenant.existingSecret) .Values.multiTenant.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "thclaws.fullname" . }}-hmac
  labels:
    {{- include "thclaws.labels" . | nindent 4 }}
type: Opaque
stringData:
  hmac-secret: {{ .Values.multiTenant.secret | quote }}
{{- end }}
